### ISSUE TITLE
Fatal Errors in ConfigCollector on serialize

### ISSUE THREAD

**Issue by marcuswinkler** [zendframework/ZendDeveloperTools#131]
ConfigCollector fatals with the following message if there are unserializable objects in the config:

    Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in /home/vagrant/project/vendor/zendframework/zend-developer-tools/src/ZendDeveloperTools/Profiler.php on line 213

This happens if people place instances of service factories directly into the config.
While those shouldn't be in there (to keep the config cacheable), I still think that the toolbar shouldn't crash the application if they are.

**Comment by samsonasik** [comment]
should be fixed by https://github.com/zendframework/ZendDeveloperTools/commit/d3432681aa32177a741ad23604a40af9ad454acb ? @marcuswinkler could you check re-install against dev-master ?

**Comment by marcuswinkler** [comment]
I just checked, the exception is gone in master. It is now possible to put unserializable objects into the config.
(Putting closures in the config has always been possible btw, it was closures contained in other objectes which caused the error above.)
