### ISSUE TITLE
Integrate more informations (events, file count, ...)

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/ZendDeveloperTools#133]
I think there are a more informations, which could be usefull:
- count of the classes loaded (or files)
- session / auth
- list of the fired events
    - their order
    - who catched the event

**Comment by snapshotpl** [comment]
Hi guys! I wrote module for that! https://github.com/snapshotpl/ZfSnapEventDebugger

**Comment by ThaDafinser** [comment]
All included now....thanks to @moderndeveloperllc

See https://github.com/zendframework/ZendDeveloperTools/pull/142
