### ISSUE TITLE
Creating a category entity

### ISSUE THREAD

**Issue by ManagementEngine** [zendframework/ZendDeveloperTools#143]
Hi,

When i  create a entity with the name Category in my application i get the following error:
Fatal error: require_once(): Cannot redeclare class me\entity\category in App/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php on line 197

When i disable ZendDeveloperTools the error is gone.

Gr

**Comment by akulyk** [comment]
Hi guys. I have got the same problem.
I begen to learn Zend F2. Install Dotrine 2 and got this error
Fatal error: Cannot redeclare class Blog\Entity\Article in F:\OpenServer\domains\localhost\zend2.com\module\Blog\src\Blog\Entity\Article.php on line 14

doctirne settings 
    'doctrine' => array(
        'driver' => array(
            // defines an annotation driver with two paths, and names it `my_annotation_driver`
            'Blog_entity' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
            //    'cache' => 'array',
                'paths' => array(
                    __DIR__ . '/../src/Blog/Entity'
                ),
            ),

            // default metadata driver, aggregates all other drivers into a single one.
            // Override `orm_default` only if you know what you're doing
            'orm_default' => array(
                'drivers' => array(
                    // register `my_annotation_driver` for any entity under namespace `My\Namespace`
                    'Blog\Entity' => 'Blog_entity'
                )
            )
        )
    ),

Article class

<?php

namespace Blog\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Article
 *
 * @ORM\Table(name="article", indexes={@ORM\Index(name="category", columns={"category"})})
 * @ORM\Entity
 */
class Article
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=100, nullable=false)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="article", type="text", length=65535, nullable=false)
     */
    private $article;

    /**
     * @var string
     *
     * @ORM\Column(name="short_article", type="text", length=65535, nullable=true)
     */
    private $shortArticle;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_public", type="boolean", nullable=false)
     */
    private $isPublic = '0';

    /**
     * var \Blog\Entity\Category
     *
     * @ORM\ManyToOne(targetEntity="Blog\Entity\Category")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="category", referencedColumnName="id")
     * })
     */
    private $category;



    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set article
     *
     * @param string $article
     *
     * @return Article
     */
    public function setArticle($article)
    {
        $this->article = $article;

        return $this;
    }

    /**
     * Get article
     *
     * @return string
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * Set shortArticle
     *
     * @param string $shortArticle
     *
     * @return Article
     */
    public function setShortArticle($shortArticle)
    {
        $this->shortArticle = $shortArticle;

        return $this;
    }

    /**
     * Get shortArticle
     *
     * @return string
     */
    public function getShortArticle()
    {
        return $this->shortArticle;
    }

    /**
     * Set isPublic
     *
     * @param boolean $isPublic
     *
     * return Article
     */
    public function setIsPublic($isPublic)
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    /**
     * Get isPublic
     *
     * return boolean
     */
    public function getIsPublic()
    {
        return $this->isPublic;
    }

    /**
     * Set category
     *
     * param \Blog\Entity\Category $category
     *
     * return Article
     */
    public function setCategory(\Blog\Entity\Category $category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \Blog\Entity\Category
     */
    public function getCategory()
    {
        return $this->category;
    }
}

if do not use Zend Developer Tools everything is fine, but this is a bad idea.

 Help needed!!!

**Comment by akulyk** [comment]
![2016-12-18 15 39 35](https://cloud.githubusercontent.com/assets/7733585/21293878/3c11c868-c538-11e6-9f00-6e721ce2e7a0.png)

**Comment by Ocramius** [comment]
As you can see, it's choking on the autoloader. Probably trying to load the same file twice. You can see what this is doing by adding a no-op autoloader that simply logs all autoload attempts and their traces.

**Comment by akulyk** [comment]
thanks @Ocramius . But how can i do it?

**Comment by akulyk** [comment]
or maybe the broblem is that doctrine generates php vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Blog\\Entity\\"  --from-database annotation module/Blog/src/
Processing entity "Blog\\Entity\Article"
instead of  Blog\Entity\Article
so ZendAutoloader trys to load Blog\\Entity\Article

Yes it is!!!

Problem solved!!! 
php vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Blog\Entity\\"  --from-database annotation module/Blog/src/ was the right command
--namespace="Blog\\Entity\\" is wrong!!!

Everyone thanks a lot and sorry for trouble
