### ISSUE TITLE
ZendDeveloper + simpleXml

### ISSUE THREAD

**Issue by llpereiras** [zendframework/ZendDeveloperTools#159]
in this line
```php
return simplexml_load_string($str);
```

```
Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in C:\wamp\www\aprendacerto\vendor\ZendDeveloperTools\src\ZendDeveloperTools\Collector\DbCollector.php on line 136
( ! ) Exception: Serialization of 'SimpleXMLElement' is not allowed in C:\wamp\www\aprendacerto\vendor\ZendDeveloperTools\src\ZendDeveloperTools\Collector\DbCollector.php on line 136
```

**Comment by moderndeveloperllc** [comment]
@Ocramius Sorry for being dense. It's been quite a while since I looked at all this code. Why is the profiler being serialized? Would something as simple as `json_encode()` fix this?

**Comment by Ocramius** [comment]
@moderndeveloperllc the profiler is being serialized to keep a snapshot of the data at the time where is relevant for us (to see what's going on). If that doesn't happen, then it is not possible to dump accurate information.

**Comment by moderndeveloperllc** [comment]
I guess the question is if further development should be done on this repo, or just have folks focus issues/PRs on Roave/RoaveDeveloperTools as you already solved this issue there with `ObjectStub` et al.

**Comment by Ocramius** [comment]
@moderndeveloperllc I'd rather fix it here and add a test there (should already work).

Yes, Roave/RoaveDeveloperTools will supersede this repo, but I don't have time for it right now.

**Comment by seyfer** [comment]
I have the same error right now.

**Comment by seyfer** [comment]
It can be fixed with something like that wrapping, but I don't know exactly where in code

```
if ($var instanceof \SimpleXmlElement)
{
 $var = var_export($var);
}
```

**Comment by seyfer** [comment]
My error full text.

```
Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /var/www/sss.com/vendor/zendframework/zend-developer-tools/src/ZendDeveloperTools/Profiler.php on line 212
( ! ) Exception: Serialization of 'SimpleXMLElement' is not allowed in /var/www/sss.com/vendor/zendframework/zend-developer-tools/src/ZendDeveloperTools/Profiler.php on line 212
```

**Comment by seyfer** [comment]
I am just removed `unserialize(serialize())` and that do the trick, all works now.

**Comment by Ocramius** [comment]
Was handled in #190
