### ISSUE TITLE
Create collector via factory got error object as null in call dependency

### ISSUE THREAD

**Issue by samsonasik** [zendframework/ZendDeveloperTools#178]
Hi,
I'm trying to create collector with factory, but it got error on calling the object dependency like reported here https://github.com/samsonasik/SanSessionToolbar/issues/20 . Probably related with #153 ?

**Comment by samsonasik** [comment]
this is related with https://github.com/zendframework/ZendDeveloperTools/blob/master/src/ZendDeveloperTools/Profiler.php#L212 , any reason for : 
```php
unserialize(serialize($collector))
```
?

**Comment by Ocramius** [comment]
The reason for  `unserialize(serialize($collector))` is that the collectors may be persisted/logged.

While this may seem a dumb idea, that was the initial aim of this package, which I also re-iterated in [RoaveDeveloperTools](https://github.com/Roave/RoaveDeveloperTools) later on.

**Comment by samsonasik** [comment]
closing, should be fixed by #190
