### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by samsonasik** [zendframework/ZendDeveloperTools#182]
@Ocramius as we have started tests, could we have travis build too?

**Comment by Ocramius** [comment]
@samsonasik I don't have the rights to turn it on

**Comment by weierophinney** [comment]
I've enabled it now; if somebody provides the travis config, it will start triggering.

**Comment by gianarb** [comment]
Thanks!! :D

**Comment by samsonasik** [comment]
Thanks @weierophinney
