### ISSUE TITLE
ZendDeveloperTools not "working" with ViewJsonStrategy

### ISSUE THREAD

**Issue by ibekiaris** [zendframework/ZendDeveloperTools#189]
Is there a simple way to display ZendDeveloperTools bar when 'ViewJsonStrategy' is set?

Thanks in advance!

**Comment by Ocramius** [comment]
It shouldn't actually work: it's disabled if the output isn't HTML.

**Comment by ibekiaris** [comment]
Oh i see. So its useless when creating for example Restful API. Is there any alternative to that tool bar (Working with Zend2)?

**Comment by Ocramius** [comment]
@ibekiaris I was working on https://github.com/Roave/RoaveDeveloperTools last year, but I never got anywhere due to time constraints and lack of help.

That component properly saves dumps of information and makes them available in the toolbar in other requests.

**Comment by seyfer** [comment]
Same issue for me

**Comment by gianarb** [comment]
I don't know if It is an issue.. This module works in this way..
