### ISSUE TITLE
Strange 'not showing' issue on project

### ISSUE THREAD

**Issue by seyfer** [zendframework/ZendDeveloperTools#195]
I have a project and development config for it with ZendDeveloperTools enabled

```
// Development time modules
    'modules'                 => [
        'ZendDeveloperTools',
        'SanSessionToolbar',
    ],
```

It's installed with composer of course (dev-master).

So, the issue is: when I'm on authorization screen or any, but not authorized - I have toolbar visible and working, after authorization it's not working.
  Also I did html source code exploration and found there css and js generated for toolbar. 
But after authorization there only css generated in output, but no js, that's why toolbar missing.
But I can't find why it's happening. I have all php errors visible - there no erros, just no js generated and no toolbar. 
If I log out - toolbar visible again. >_<

I'm already tried anything and google all google through.. And I haven't this issue on other projects yet.

**Comment by Ocramius** [comment]
Is the inject toolbar listener called at all?

**Comment by seyfer** [comment]
@Ocramius , I don't understand about what listener you talk. 
What can cause no js generattion for toolbar, but only css ?

**Comment by Ocramius** [comment]
@seyfer see https://github.com/zendframework/ZendDeveloperTools/blob/a3399877d69491acdac86e3aead53937c16b0303/src/ZendDeveloperTools/Listener/ToolbarListener.php#L147-L171

**Comment by seyfer** [comment]
@Ocramius thank you, I has just debugged it and found that `body` close tag was missing in layout.phtml. `</body>` was missing... 
Maybe some checks should be added to this method, because this problem was silent and takes 2 weeks to solve. If you agree, I will add checks that html is correct and all injects passed, otherwise exception will be throw. 
Can I add it by pull request?

**Comment by Ocramius** [comment]
No exception should be thrown: the tool should simply allow also invalid
html.

**Comment by seyfer** [comment]
I will try to fix preg_match pattern than

**Comment by Ocramius** [comment]
The toolbar should not be injected if there is no closing body tag.

**Comment by seyfer** [comment]
User should be noticed about that, because it's very confusing and hard to find problem!

**Comment by Ocramius** [comment]
You'd simply break everyone's code: templates are used also in
partial/ajax/esi context. This is a bug in your code, not in the component.

**Comment by seyfer** [comment]
But component should be smart and not hide problem. How I can guess there no close body tag in some big project and why toolbar not working? I need spend time for debugging? You think this is reasonable behavior?

**Comment by Ocramius** [comment]
It is indeed reasonable behavior, as the source of the bug is in your code.

Again, breaking partial templates because you had a bad day (debugging YOUR
code) is NOT solved by making a component that isn't strict by design
strict.

**Comment by seyfer** [comment]
It's not about just my bad day, anyone can face with this problem. 
At least code could do echo with some text inside comments `<!-- -->` with error description if some injection failed. It's not visible and not break anything in html strategy, but informative. For other cases other output could be provided. I think there is some way exist to make it better, not just silent wtf bug if something go wrong.

But as you wish .. whatever. Thank for support.
