### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by samsonasik** [zendframework/ZendDeveloperTools#196]
Hi, any chance to make new release ? 1.0.0 ?

**Comment by samsonasik** [comment]
anyone have a chance to make a new release ?

**Comment by Ocramius** [comment]
I just released 1.0.0-RC1 (due to the number of changes, I couldn't just jump to 1.0.0)

**Comment by Ocramius** [comment]
I just released 1.0.0-RC1 (due to the number of changes, I couldn't just jump to 1.0.0)

**Comment by samsonasik** [comment]
@Ocramius thank you ;)
