### ISSUE TITLE
zend-servicemanager v3 and zend-eventmanager v3 support

### ISSUE THREAD

**Issue by samsonasik** [zendframework/ZendDeveloperTools#207]
I tried with zend-servicemanager and zend-eventmanager v3, got many errors. Seems we need to provide support for them?

**Comment by gianarb** [comment]
And for expressive is impossibile? I don't use expressive at the moment it's only an idea :) I don't know if it is impossibile

**Comment by samsonasik** [comment]
zdt is not for expressive, for expressive, there is a way to provide debug toolbar for that: https://zendframework.github.io/zend-expressive/cookbook/debug-toolbars/ .
mostly, the issue on zdt usage is on zend-eventmanager->attach() BC break

**Comment by gianarb** [comment]
ok Thanks

**Comment by NewtonsNerds** [comment]
+1 for the issue rising, I noticed ZDT is no longer compatible with DoctrineORMModule after an update of ZF2, disable ZDT will remove this error:

This happened when I was at zfcuser login page with ZDT enabled.

> Fatal error: Call to a member function getName() on a non-object in D:\xampp\htdocs\TMS2\vendor\doctrine\doctrine-orm-module\src\DoctrineORMModule\Yuml\MetadataGrapher.php on line 152

**Comment by Mondane** [comment]
@NewtonsNerds Disabling ZDT removes the error but also the usefull toolbar. Did you find a solution to keep using ZDT?
