### ISSUE TITLE
Argument 1 passed to ZendDeveloperTools\Exception\SerializableException::__construct() must be an instance of Exception

### ISSUE THREAD

**Issue by seaneble** [zendframework/ZendDeveloperTools#216]
The phenomenon of #10 (supposedly fixed since 2012) happens again. I'm running the current master branch, it started to appear some weeks ago.

Any time the application generates an exception, the toolbar blocks it and only shows

    Fatal error: Uncaught TypeError: Argument 1 passed to ZendDeveloperTools\Exception\SerializableException::__construct() must be an instance of Exception, instance of Error given, called in /…/vendor/zendframework/zend-developer-tools/src/Collector/ExceptionCollector.php on line 45 and defined in /…/vendor/zendframework/zend-developer-tools/src/Exception/SerializableException.php:26 Stack trace:
    #0 /…/vendor/zendframework/zend-developer-tools/src/Collector/ExceptionCollector.php(45): ZendDeveloperTools\Exception\SerializableException->__construct(Object(Error))
    #1 /…/vendor/zendframework/zend-developer-tools/src/Profiler.php(210): ZendDeveloperTools\Collector\ExceptionCollector->collect(Object(Zend\Mvc\MvcEvent))
    #2 /…/vendor/zendframework/zend-developer-tools/src/Listener/ProfilerListener.php(93): ZendDeveloperTools\Profiler->collect(Object(Zend\Mvc\MvcEvent))
    #3 [ in /…/vendor/zendframework/zend-developer-tools/src/Exception/SerializableException.php on line 26

**Comment by technoboy2084** [comment]
I've got the same problem, i suggest to modify the argument type in the constructor from
```php
public function __construct(\Exception $exception)
```
to
```php
public function __construct(\Throwable $exception)
```

**Comment by samsonasik** [comment]
there is no `Throwable` in php 5.6, maybe just remove the type hint ?

**Comment by Ocramius** [comment]
Could also drop PHP 5.x :trollface: 

But yeah, should be just dropping the type-hint if we want to support 5.x

**Comment by samsonasik** [comment]
@Ocramius  I've create PR #217 for it.

**Comment by seaneble** [comment]
Great, thanks! What are your release cycles? How long does it usually take to wrap this into a release?

**Comment by samsonasik** [comment]
@Ocramius may know about that, but if you need the patch now, you can do the following update.
- update dependency to:
```javascript
"zendframework/zend-developer-tools": "dev-patch-3"
```
- update repository url in composer.json:
```javascript
"repositories" : [ {
    "type" : "vcs",
 "url" : "git@github.com:samsonasik/ZendDeveloperTools.git"
}]
```
- composer update

**Comment by seaneble** [comment]
Thanks, the fix works.
