### ISSUE TITLE
Show all routing parameters

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/ZendDeveloperTools#219]
Since a long time, I am really missing the feature that shows all routing params. Currently we only get the `controller` and the `action`. But `id` parameters or others are not shown.

**Comment by samsonasik** [comment]
I've created PR #220 for that, also fixes the zdt-toolbar-info-redundant class that only show 1st record.

**Comment by RalfEggert** [comment]
Great! :+1: 

Looks great!
