### ISSUE TITLE
ZF3 support

### ISSUE THREAD

**Issue by jarrettj** [zendframework/ZendDeveloperTools#228]
Hi,

Good day.

Any chance ZF3 will be supported in the future? Thanks.

**Comment by kokspflanze** [comment]
@jarrettj did you checked https://github.com/zendframework/ZendDeveloperTools/releases/tag/1.1.0 ? zf3 is already supported

**Comment by jarrettj** [comment]
@kokspflanze thanks dude! My eye sight! I see it now on composer site. :)
