### ISSUE TITLE
Blog guide- ZF2,  An exception was raised while creating "Blog\Controller\List"; no instance returned

### ISSUE THREAD

**Issue by monteiro07** [zendframework/ZendDeveloperTools#239]
Hi, i have been following step by step the Zend Framework 2 beginners guide, found on the ZF homepage, and i got stuck on the following bugg:  An exception was raised while creating "Blog\Controller\List"; no instance returned.

[config.txt](https://github.com/zendframework/ZendDeveloperTools/files/824114/config.txt)
[ListController.txt](https://github.com/zendframework/ZendDeveloperTools/files/824115/ListController.txt)

[PostInterface.txt](https://github.com/zendframework/ZendDeveloperTools/files/824117/PostInterface.txt)
[PostMapperInterface.txt](https://github.com/zendframework/ZendDeveloperTools/files/824116/PostMapperInterface.txt)
[PostService.txt](https://github.com/zendframework/ZendDeveloperTools/files/824118/PostService.txt)
[PostServiceFactory.txt](https://github.com/zendframework/ZendDeveloperTools/files/824119/PostServiceFactory.txt)

i attach the main code files to this message, on a txt formmat.
Any help apreciated.
Thank you for your time.

**Comment by asgrim** [comment]
@monteiro07 this isn't relevant for this repository; nor are issue trackers good places for help. It might be prudent to try the #zftalk IRC channel on Freenode!
