### ISSUE TITLE
1.2.0 release causes ServiceNotFoundException for ZendDeveloperTools\Listener\ProfilerListener

### ISSUE THREAD

**Issue by walberty** [zendframework/ZendDeveloperTools#247]
#237, included in the recent 1.2.0 release, changes several string aliases to FQCNs, but the corresponding changes were not made in the `factories` section of `getServiceConfig()`, causing a `Zend\ServiceManager\Exception\ServiceNotFoundException` to be thrown at module initialization time. This renders an app unusable while in development mode.

https://github.com/zendframework/ZendDeveloperTools/pull/237/files#diff-2cf9f9b61ffec8561183510e290d9bb0L107 requires a corresponding change here: https://github.com/zendframework/ZendDeveloperTools/blob/master/src/Module.php#L184

Additionally, https://github.com/zendframework/ZendDeveloperTools/pull/237/files#diff-2cf9f9b61ffec8561183510e290d9bb0L111 changes the ToolbarListener to the wrong class, and also needs the corresponding change in the factories section.

**Comment by froschdesign** [comment]
@samsonasik 
Can you look at this? Thanks! 😃

**Comment by samsonasik** [comment]
@froschdesign it seems there is already PR #248 for it
