### ISSUE TITLE
Is it possible to collect (doctrine) queries in AJAX requests and adding those to the toolbar on the current page?

### ISSUE THREAD

**Issue by pietervogelaar** [zendframework/ZendDeveloperTools#73]

**Comment by Blaimi** [comment]
What about sending a cookie with a uuid within the initial request of the page. After that we can store the information in some cached mini-dumps in /data for each uuid and display all the stuff on a different page (with uuid in the route?) accessible by a link on the toolbar. This page could look like a stack of toolbars, representing a single request each (which will look very ugly, but will be functional). This can also solve Problems with pages which cannot display the toolbar.

![mockup ajax-dev-tools](https://cloud.githubusercontent.com/assets/1222379/14884176/4f1cdd1a-0d43-11e6-8a3b-abed3167bced.png)
